begin;

create table if not exists public.smax_auto_tag_rules (
  id bigint generated by default as identity primary key,
  tag_label text not null unique,
  keywords text[] not null default '{}',
  sort_order int not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.smax_auto_tag_rules (tag_label, keywords, sort_order, is_active)
values
  ('CEMAN', array['mandado','oficial de justica','central de mandos'], 1, true),
  ('CUSTAS', array['custas','taxa','diligencia','diligencias'], 2, true),
  ('ATP', array['atp','automatizacao','automacao','regra'], 3, true),
  ('CADASTROS', array['cadastrar','cadastro'], 4, true),
  ('LOGIN', array['acesso','login','acessar','fatores','autenticador','autenticacao','authenticator','senha'], 5, true),
  ('MIGRADOR', array['migrado','migrados','migracao','migrador','migrar'], 6, true),
  ('CORREIOS', array['carta','cartas'], 7, true),
  ('DJEN', array['djen'], 8, true),
  ('ACIONAMENTOS', array['renajud','sisbajud'], 9, true),
  ('DISTRIBUICAO', array['distribuicao','redistribuir','remeter'], 10, true)
on conflict (tag_label) do update
set
  keywords = excluded.keywords,
  sort_order = excluded.sort_order,
  is_active = excluded.is_active,
  updated_at = now();

commit;
