-- SMAX SGS 221 - initial schema and seed
-- Covers:
-- - teams
-- - specialists (with colors, nickname, absence)
-- - specialist finals (0-99)
-- - highlight groups and terms (whole/substr/regex)
-- - detractors
-- - feature prefs

begin;

-- 1) Teams
create table if not exists public.smax_teams (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- 2) Specialists
create table if not exists public.smax_specialists (
  id bigint generated by default as identity primary key,
  team_id bigint not null references public.smax_teams(id) on delete cascade,
  name text not null,
  nickname text not null default '',
  bg_color text not null default '#E2E8F0',
  fg_color text not null default '#111111',
  is_absent boolean not null default false,
  sort_order int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint smax_specialists_team_name_uniq unique (team_id, name)
);

create index if not exists smax_specialists_team_idx on public.smax_specialists(team_id);

-- 3) Finals by specialist
create table if not exists public.smax_specialist_finals (
  specialist_id bigint not null references public.smax_specialists(id) on delete cascade,
  final smallint not null check (final between 0 and 99),
  created_at timestamptz not null default now(),
  primary key (specialist_id, final)
);

-- 4) Highlight groups
create table if not exists public.smax_highlight_groups (
  id bigint generated by default as identity primary key,
  group_key text not null unique,
  label text not null,
  css_class text not null,
  sort_order int not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- 5) Highlight terms
-- match_type:
-- - whole  : whole token match
-- - substr : partial contains
-- - regex  : regex pattern in term (+ optional flags)
create table if not exists public.smax_highlight_terms (
  id bigint generated by default as identity primary key,
  group_id bigint not null references public.smax_highlight_groups(id) on delete cascade,
  match_type text not null check (match_type in ('whole', 'substr', 'regex')),
  term text not null,
  regex_flags text not null default '',
  sort_order int not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  constraint smax_highlight_terms_uniq unique (group_id, match_type, term, regex_flags)
);

create index if not exists smax_highlight_terms_group_idx on public.smax_highlight_terms(group_id);

-- 6) Detractors
create table if not exists public.smax_detractors (
  id bigint generated by default as identity primary key,
  full_name text not null unique,
  sort_order int not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

-- 7) Global feature prefs currently used by the script
create table if not exists public.smax_feature_prefs (
  id int primary key check (id = 1),
  highlights_on boolean not null default true,
  name_badges_on boolean not null default true,
  magistrado_on boolean not null default true,
  collapse_on boolean not null default true,
  enlarge_comments_on boolean not null default true,
  auto_tags_on boolean not null default true,
  updated_at timestamptz not null default now()
);

-- Team seed
insert into public.smax_teams (code, name)
values
  ('SGS 2.2.1', 'SGS 2.2.1'),
  ('SGS 2.2.2', 'SGS 2.2.2')
on conflict (code) do update
set
  name = excluded.name,
  updated_at = now();

-- Specialist seed from current script defaults (assigned to SGS 2.2.1)
with team as (
  select id
  from public.smax_teams
  where code = 'SGS 2.2.1'
),
src(name, nickname, bg_color, fg_color, is_absent, sort_order) as (
  values
    ('ADRIANO', '', '#E6E66A', '#000', false,  1),
    ('DANIEL LEAL', '', '#E6A85C', '#000', false,  2),
    ('DOUGLAS MACHADO', '', '#66CCCC', '#000', false,  3),
    ('DOUGLAS SUGAHARA', '', '#4FA6A6', '#fff', false,  4),
    ('IONE', '', '#4D4D4D', '#fff', true,  5),
    ('ISA', '', '#5C6FA6', '#fff', true,  6),
    ('IVAN', '', '#9A9A52', '#000', false,  7),
    ('LAIS AKEMI', '', '#D966D9', '#000', false,  8),
    ('LAIS MARTINS', '', '#B85CB8', '#fff', false,  9),
    ('LEONARDO', '', '#8E5A8E', '#fff', false, 10),
    ('LUANA', '', '#7ACC7A', '#000', false, 11),
    ('LUIS FELIPE', '', '#5CA3A3', '#000', false, 12),
    ('MARCELO', '', '#A05252', '#fff', false, 13),
    ('MARLON', '', '#A0A0A0', '#000', false, 14),
    ('ROBSON', '', '#CCCCCC', '#000', false, 15),
    ('RODRIGO', '', '#999999', '#000', false, 16),
    ('SAMUEL', '', '#66A3CC', '#000', false, 17),
    ('YVES', '', '#2F4F8F', '#fff', false, 18)
)
insert into public.smax_specialists (
  team_id, name, nickname, bg_color, fg_color, is_absent, sort_order
)
select
  team.id, src.name, src.nickname, src.bg_color, src.fg_color, src.is_absent, src.sort_order
from src
cross join team
on conflict (team_id, name) do update
set
  nickname = excluded.nickname,
  bg_color = excluded.bg_color,
  fg_color = excluded.fg_color,
  is_absent = excluded.is_absent,
  sort_order = excluded.sort_order,
  updated_at = now();

-- Finals seed from current script defaults
with team as (
  select id
  from public.smax_teams
  where code = 'SGS 2.2.1'
),
src(name, finals) as (
  values
    ('ADRIANO',          array[0,1,2,3,4,5]::smallint[]),
    ('DANIEL LEAL',      array[6,7,8,9,10]::smallint[]),
    ('DOUGLAS MACHADO',  array[11,12,13,14,15]::smallint[]),
    ('DOUGLAS SUGAHARA', array[16,17,18,19,20,21]::smallint[]),
    ('IONE',             array[22,23,24,25,26]::smallint[]),
    ('ISA',              array[27,28,29,30,31,32]::smallint[]),
    ('IVAN',             array[33,34,35,36,37,38]::smallint[]),
    ('LAIS AKEMI',       array[39,40,41,42,43]::smallint[]),
    ('LAIS MARTINS',     array[44,45,46,47,48,49]::smallint[]),
    ('LEONARDO',         array[50,51,52,53,54,55]::smallint[]),
    ('LUANA',            array[56,57,58,59,60]::smallint[]),
    ('LUIS FELIPE',      array[61,62,63,64,65,66]::smallint[]),
    ('MARCELO',          array[67,68,69,70,71,72]::smallint[]),
    ('MARLON',           array[73,74,75,76,77]::smallint[]),
    ('ROBSON',           array[78,79,80,81,82,83]::smallint[]),
    ('RODRIGO',          array[84,85,86,87,88]::smallint[]),
    ('SAMUEL',           array[89,90,91,92,93,94]::smallint[]),
    ('YVES',             array[95,96,97,98,99]::smallint[])
),
spec as (
  select s.id as specialist_id, src.finals
  from src
  join team on true
  join public.smax_specialists s
    on s.team_id = team.id
   and s.name = src.name
)
insert into public.smax_specialist_finals (specialist_id, final)
select specialist_id, unnest(finals) as final
from spec
on conflict (specialist_id, final) do nothing;

-- Highlight groups
insert into public.smax_highlight_groups (group_key, label, css_class, sort_order)
values
  ('vermelho', 'Vermelho', 'tmx-hl-red', 1),
  ('rosa',     'Rosa',     'tmx-hl-pink', 2),
  ('amarelo',  'Amarelo',  'tmx-hl-yellow', 3),
  ('verde',    'Verde',    'tmx-hl-green', 4),
  ('azul',     'Azul',     'tmx-hl-blue', 5)
on conflict (group_key) do update
set
  label = excluded.label,
  css_class = excluded.css_class,
  sort_order = excluded.sort_order,
  updated_at = now();

-- Highlight terms (whole)
with g as (
  select id, group_key
  from public.smax_highlight_groups
),
src(group_key, match_type, term, regex_flags, sort_order) as (
  values
    ('amarelo', 'whole', 'jurisprudencia', '', 1),
    ('amarelo', 'whole', 'distribuidor', '', 2),
    ('amarelo', 'whole', 'acessar', '', 3),
    ('amarelo', 'whole', 'djen', '', 4),
    ('amarelo', 'whole', 'diario eletronico', '', 5),
    ('amarelo', 'whole', 'automatizacao', '', 6),
    ('amarelo', 'whole', 'ceman', '', 7),
    ('amarelo', 'whole', 'central de mandados', '', 8),
    ('amarelo', 'whole', 'mandado', '', 9),
    ('amarelo', 'whole', 'mandados', '', 10),
    ('amarelo', 'whole', 'movimentar', '', 11),
    ('amarelo', 'whole', 'dois fatores', '', 12),
    ('amarelo', 'whole', 'renajud', '', 13),
    ('amarelo', 'whole', 'sisbajud', '', 14),
    ('amarelo', 'whole', 'autenticador', '', 15),
    ('amarelo', 'whole', 'carta', '', 16),
    ('amarelo', 'whole', 'evento', '', 17),
    ('amarelo', 'whole', 'cadastro', '', 18),
    ('amarelo', 'whole', 'automacao', '', 19),
    ('amarelo', 'whole', 'automacoes', '', 20),
    ('amarelo', 'whole', 'migrar', '', 21),
    ('amarelo', 'whole', 'migrador', '', 22),
    ('amarelo', 'whole', 'migracao', '', 23),
    ('amarelo', 'whole', 'perito', '', 24),
    ('amarelo', 'whole', 'perita', '', 25),
    ('amarelo', 'whole', 'localizadores', '', 26),
    ('amarelo', 'whole', 'localizador', '', 27),

    ('vermelho', 'whole', 'erro_agendamento_evento', '', 1),
    ('vermelho', 'whole', 'erro_envio_intimacao_djen', '', 2),
    ('vermelho', 'whole', 'item 04 do comunicado 435/2025', '', 3),
    ('vermelho', 'whole', 'erro ao gerar o documento comprobatario renajud', '', 4),
    ('vermelho', 'whole', 'cookie not found', '', 5),
    ('vermelho', 'whole', 'urgente', '', 6),
    ('vermelho', 'whole', 'urgencia', '', 7),
    ('vermelho', 'whole', 'plantao', '', 8),

    ('verde', 'whole', 'taxa', '', 1),
    ('verde', 'whole', 'taxas', '', 2),
    ('verde', 'whole', 'custa', '', 3),
    ('verde', 'whole', 'custas', '', 4),
    ('verde', 'whole', 'restituir', '', 5),
    ('verde', 'whole', 'restituicao', '', 6),
    ('verde', 'whole', 'guia', '', 7),
    ('verde', 'whole', 'diligencia', '', 8),
    ('verde', 'whole', 'justica gratuita', '', 9),
    ('verde', 'whole', 'parcelamento', '', 10),
    ('verde', 'whole', 'parcelamento das custas', '', 11),
    ('verde', 'whole', 'desvincular', '', 12),
    ('verde', 'whole', 'desvinculacao', '', 13),

    ('azul', 'whole', 'magistrado', '', 1),
    ('azul', 'whole', 'magistrada', '', 2),

    ('rosa', 'whole', 'inesperado', '', 1),

    ('amarelo', 'substr', 'acess', '', 1),
    ('amarelo', 'substr', 'mail', '', 2),

    ('vermelho', 'substr', 'erro', '', 1),
    ('vermelho', 'substr', 'errado', '', 2),
    ('vermelho', 'substr', 'reu revel', '', 3),
    ('vermelho', 'substr', 'help_outline', '', 4),

    ('azul', 'regex', '\\bju[ií]z(?:es|a)?\\b', 'giu', 1)
)
insert into public.smax_highlight_terms (group_id, match_type, term, regex_flags, sort_order)
select g.id, src.match_type, src.term, src.regex_flags, src.sort_order
from src
join g on g.group_key = src.group_key
on conflict (group_id, match_type, term, regex_flags) do update
set
  sort_order = excluded.sort_order,
  is_active = true;

-- Detractors
with src(full_name, sort_order) as (
  values
    ('Adriano Zilli', 1),
    ('Adriana Da Silva Ferreira Oliveira', 2),
    ('Alessandra Sousa Nunes', 3),
    ('Bruna Marques Dos Santos', 4),
    ('Breno Medeiros Malfati', 5),
    ('Carlos Henrique Scala De Almeida', 6),
    ('Cassia Santos Alves De Lima', 7),
    ('Dalete Rodrigues Silva', 8),
    ('David Lopes De Oliveira', 9),
    ('Davi Dos Reis Garcia', 10),
    ('Deaulas De Campos Salviano', 11),
    ('Diego Oliveira Da Silva', 12),
    ('Diogo Mendonca Aniceto', 13),
    ('Elaine Moriya', 14),
    ('Ester Naili Dos Santos', 15),
    ('Fabiano Barbosa Dos Reis', 16),
    ('Fabricio Christiano Tanobe Lyra', 17),
    ('Gabriel Teixeira Ludvig', 18),
    ('Gilberto Sintoni Junior', 19),
    ('Giovanna Coradini Teixeira', 20),
    ('Gislene Ferreira Sant''Ana Ramos', 21),
    ('Guilherme Cesar De Sousa', 22),
    ('Gustavo De Meira Goncalves', 23),
    ('Jackson Alcantara Santana', 24),
    ('Janaina Dos Passos Silvestre', 25),
    ('Jefferson Silva De Carvalho Soares', 26),
    ('Joyce Da Silva Oliveira', 27),
    ('Juan Campos De Souza', 28),
    ('Juliana Lino Dos Santos Rosa', 29),
    ('Karina Nicolau Samaan', 30),
    ('Karine Barbara Vitor De Lima Souza', 31),
    ('Kaue Nunes Silva Farrelly', 32),
    ('Kelly Ferreira De Freitas', 33),
    ('Larissa Ferreira Fumero', 34),
    ('Lucas Alves Dos Santos', 35),
    ('Lucas Carneiro Peres Ferreira', 36),
    ('Marcos Paulo Silva Madalena', 37),
    ('Maria Fernanda De Oliveira Bento', 38),
    ('Natalia Yurie Shiba', 39),
    ('Paulo Roberto Massoca', 40),
    ('Pedro Henrique Palacio Baritti', 41),
    ('Rafaella Silva Lima Petrolini', 42),
    ('Renata Aparecida Mendes Bonvechio', 43),
    ('Rodrigo Silva Oliveira', 44),
    ('Ryan Souza Carvalho', 45),
    ('Tatiana Lourenco Da Costa Antunes', 46),
    ('Tatiane Araujo Da Cruz', 47),
    ('Thiago Tadeu Faustino De Oliveira', 48),
    ('Tiago Carvalho De Freitas Meneses', 49),
    ('Victor Viana Roca', 50),
    ('GERSON DA MATTA', 51),
    ('ROGE NAIM TENN', 52)
)
insert into public.smax_detractors (full_name, sort_order)
select full_name, sort_order
from src
on conflict (full_name) do update
set
  sort_order = excluded.sort_order,
  is_active = true;

-- Feature prefs defaults from script
insert into public.smax_feature_prefs (
  id,
  highlights_on,
  name_badges_on,
  magistrado_on,
  collapse_on,
  enlarge_comments_on,
  auto_tags_on
)
values (1, true, true, true, true, true, true)
on conflict (id) do update
set
  highlights_on = excluded.highlights_on,
  name_badges_on = excluded.name_badges_on,
  magistrado_on = excluded.magistrado_on,
  collapse_on = excluded.collapse_on,
  enlarge_comments_on = excluded.enlarge_comments_on,
  auto_tags_on = excluded.auto_tags_on,
  updated_at = now();

commit;
