begin;

create table if not exists public.smax_specialist_tags (
  id bigint generated by default as identity primary key,
  specialist_id bigint not null references public.smax_specialists(id) on delete cascade,
  tag_label text not null,
  sort_order int not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint smax_specialist_tags_uniq unique (specialist_id, tag_label)
);

create index if not exists smax_specialist_tags_specialist_idx
  on public.smax_specialist_tags(specialist_id);

create table if not exists public.smax_specialist_tag_keywords (
  id bigint generated by default as identity primary key,
  specialist_tag_id bigint not null references public.smax_specialist_tags(id) on delete cascade,
  keyword text not null,
  sort_order int not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint smax_specialist_tag_keywords_uniq unique (specialist_tag_id, keyword)
);

create index if not exists smax_specialist_tag_keywords_tag_idx
  on public.smax_specialist_tag_keywords(specialist_tag_id);

do $$
begin
  if exists (
    select 1
    from information_schema.tables
    where table_schema = 'public'
      and table_name = 'smax_specialist_tag_rules'
  ) then
    insert into public.smax_specialist_tags (
      specialist_id,
      tag_label,
      sort_order,
      is_active
    )
    select
      r.specialist_id,
      r.tag_label,
      r.sort_order,
      r.is_active
    from public.smax_specialist_tag_rules r
    on conflict (specialist_id, tag_label) do update
    set
      sort_order = excluded.sort_order,
      is_active = excluded.is_active,
      updated_at = now();

    insert into public.smax_specialist_tag_keywords (
      specialist_tag_id,
      keyword,
      sort_order,
      is_active
    )
    select
      t.id as specialist_tag_id,
      kw.keyword,
      kw.sort_order,
      r.is_active
    from public.smax_specialist_tag_rules r
    join public.smax_specialist_tags t
      on t.specialist_id = r.specialist_id
     and t.tag_label = r.tag_label
    cross join lateral (
      select
        trim(value) as keyword,
        ord::int as sort_order
      from unnest(coalesce(r.keywords, '{}')) with ordinality as words(value, ord)
    ) kw
    where kw.keyword <> ''
    on conflict (specialist_tag_id, keyword) do update
    set
      sort_order = excluded.sort_order,
      is_active = excluded.is_active,
      updated_at = now();
  elsif exists (
    select 1
    from information_schema.tables
    where table_schema = 'public'
      and table_name = 'smax_auto_tag_rules'
  ) then
    insert into public.smax_specialist_tags (
      specialist_id,
      tag_label,
      sort_order,
      is_active
    )
    select
      s.id as specialist_id,
      r.tag_label,
      r.sort_order,
      r.is_active
    from public.smax_specialists s
    cross join public.smax_auto_tag_rules r
    on conflict (specialist_id, tag_label) do update
    set
      sort_order = excluded.sort_order,
      is_active = excluded.is_active,
      updated_at = now();

    insert into public.smax_specialist_tag_keywords (
      specialist_tag_id,
      keyword,
      sort_order,
      is_active
    )
    select
      t.id as specialist_tag_id,
      kw.keyword,
      kw.sort_order,
      r.is_active
    from public.smax_auto_tag_rules r
    join public.smax_specialist_tags t
      on t.tag_label = r.tag_label
    cross join lateral (
      select
        trim(value) as keyword,
        ord::int as sort_order
      from unnest(coalesce(r.keywords, '{}')) with ordinality as words(value, ord)
    ) kw
    where kw.keyword <> ''
    on conflict (specialist_tag_id, keyword) do update
    set
      sort_order = excluded.sort_order,
      is_active = excluded.is_active,
      updated_at = now();
  end if;
end $$;

commit;
