begin;

create table if not exists public.smax_specialist_highlight_terms (
  id bigint generated by default as identity primary key,
  specialist_id bigint not null references public.smax_specialists(id) on delete cascade,
  group_id bigint not null references public.smax_highlight_groups(id) on delete cascade,
  match_type text not null check (match_type in ('whole', 'substr', 'regex')),
  term text not null,
  regex_flags text not null default '',
  sort_order int not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint smax_specialist_highlight_terms_uniq unique (specialist_id, group_id, match_type, term, regex_flags)
);

create index if not exists smax_specialist_highlight_terms_specialist_idx
  on public.smax_specialist_highlight_terms(specialist_id);

create index if not exists smax_specialist_highlight_terms_group_idx
  on public.smax_specialist_highlight_terms(group_id);

create table if not exists public.smax_specialist_tag_rules (
  id bigint generated by default as identity primary key,
  specialist_id bigint not null references public.smax_specialists(id) on delete cascade,
  tag_label text not null,
  keywords text[] not null default '{}',
  sort_order int not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint smax_specialist_tag_rules_uniq unique (specialist_id, tag_label)
);

create index if not exists smax_specialist_tag_rules_specialist_idx
  on public.smax_specialist_tag_rules(specialist_id);

do $$
begin
  if exists (
    select 1
    from information_schema.tables
    where table_schema = 'public'
      and table_name = 'smax_attendant_highlight_terms'
  ) and exists (
    select 1
    from information_schema.tables
    where table_schema = 'public'
      and table_name = 'smax_attendants'
  ) then
    insert into public.smax_specialist_highlight_terms (
      specialist_id,
      group_id,
      match_type,
      term,
      regex_flags,
      sort_order,
      is_active
    )
    select
      s.id as specialist_id,
      ht.group_id,
      ht.match_type,
      ht.term,
      coalesce(ht.regex_flags, '') as regex_flags,
      ht.sort_order,
      ht.is_active
    from public.smax_attendant_highlight_terms ht
    join public.smax_attendants a on a.id = ht.attendant_id
    join public.smax_specialists s
      on s.team_id = a.team_id
     and (
       (a.smax_person_id is not null and s.smax_person_id = a.smax_person_id)
       or upper(trim(coalesce(s.smax_person_name, s.name))) = upper(trim(coalesce(a.smax_person_name, a.name)))
     )
    on conflict (specialist_id, group_id, match_type, term, regex_flags) do update
    set
      sort_order = excluded.sort_order,
      is_active = excluded.is_active,
      updated_at = now();
  else
    insert into public.smax_specialist_highlight_terms (
      specialist_id,
      group_id,
      match_type,
      term,
      regex_flags,
      sort_order,
      is_active
    )
    select
      s.id as specialist_id,
      ht.group_id,
      ht.match_type,
      ht.term,
      coalesce(ht.regex_flags, '') as regex_flags,
      ht.sort_order,
      ht.is_active
    from public.smax_specialists s
    cross join public.smax_highlight_terms ht
    on conflict (specialist_id, group_id, match_type, term, regex_flags) do update
    set
      sort_order = excluded.sort_order,
      is_active = excluded.is_active,
      updated_at = now();
  end if;
end $$;

do $$
begin
  if exists (
    select 1
    from information_schema.tables
    where table_schema = 'public'
      and table_name = 'smax_attendant_tag_rules'
  ) and exists (
    select 1
    from information_schema.tables
    where table_schema = 'public'
      and table_name = 'smax_attendants'
  ) then
    insert into public.smax_specialist_tag_rules (
      specialist_id,
      tag_label,
      keywords,
      sort_order,
      is_active
    )
    select
      s.id as specialist_id,
      tr.tag_label,
      tr.keywords,
      tr.sort_order,
      tr.is_active
    from public.smax_attendant_tag_rules tr
    join public.smax_attendants a on a.id = tr.attendant_id
    join public.smax_specialists s
      on s.team_id = a.team_id
     and (
       (a.smax_person_id is not null and s.smax_person_id = a.smax_person_id)
       or upper(trim(coalesce(s.smax_person_name, s.name))) = upper(trim(coalesce(a.smax_person_name, a.name)))
     )
    on conflict (specialist_id, tag_label) do update
    set
      keywords = excluded.keywords,
      sort_order = excluded.sort_order,
      is_active = excluded.is_active,
      updated_at = now();
  else
    insert into public.smax_specialist_tag_rules (
      specialist_id,
      tag_label,
      keywords,
      sort_order,
      is_active
    )
    select
      s.id as specialist_id,
      tr.tag_label,
      tr.keywords,
      tr.sort_order,
      tr.is_active
    from public.smax_specialists s
    cross join public.smax_auto_tag_rules tr
    on conflict (specialist_id, tag_label) do update
    set
      keywords = excluded.keywords,
      sort_order = excluded.sort_order,
      is_active = excluded.is_active,
      updated_at = now();
  end if;
end $$;

commit;
